services:

  seat_stream:
    container_name: seat_stream
    build: .
    volumes:
      - ./seat-stream:/var/www/html
    ports:
      - 9000:80
  
  seat_stream_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seat_stream
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1